"""Initial migration

Revision ID: f1cd5176ddaf
Revises: 
Create Date: 2024-12-26 16:05:24.539370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cd5176ddaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shoe_brand', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('main_focus', sa.String(length=100), nullable=False),
    sa.Column('eco_friendly', sa.Boolean(), nullable=False),
    sa.Column('foot_type', sa.String(length=100), nullable=False),
    sa.Column('cushioning_rate', sa.Integer(), nullable=False),
    sa.Column('durability_rate', sa.Integer(), nullable=False),
    sa.Column('pace_rate', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_shoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shoe_id', sa.Integer(), nullable=False),
    sa.Column('mileage_run', sa.Float(), nullable=False),
    sa.Column('mileage_remaining', sa.Integer(), nullable=False),
    sa.Column('total_mileage_allowed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['shoe_id'], ['shoes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.Column('strava_connected', sa.Boolean(), nullable=True),
    sa.Column('main_shoe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_shoe_id'], ['user_shoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_shoes')
    op.drop_table('shoes')
    # ### end Alembic commands ###
